# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 14:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_num', models.IntegerField(default=0)),
                ('take_num', models.IntegerField(default=0)),
                ('message', models.TextField(max_length=500)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_confirm', models.BooleanField(default=False)),
                ('take_delete', models.BooleanField(default=False)),
                ('send_delete', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('send_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_message', to=settings.AUTH_USER_MODEL)),
                ('take_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='take_message', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created', '-id'),
            },
        ),
    ]
