# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 14:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(choices=[('1', '1 Round'), ('2', '2 Round'), ('3', '3 Round'), ('4', '4 Round'), ('5', '5 Round'), ('6', '6 Round'), ('7', '7 Round'), ('8', '8 Round'), ('9', '9 Round'), ('1', '10 Round'), ('11', '11 Round'), ('12', '12 Round'), ('13', '13 Round'), ('14', '14 Round'), ('15', '15 Round'), ('16', '16 Round'), ('17', '17 Round'), ('18', '18 Round'), ('19', '19 Round'), ('20', '20 Round'), ('21', '21 Round'), ('22', '22 Round'), ('23', '23 Round'), ('24', '24 Round'), ('25', '25 Round'), ('26', '26 Round'), ('27', '27 Round'), ('28', '28 Round'), ('29', '29 Round'), ('30', '30 Round'), ('31', '31 Round'), ('32', '32 Round'), ('33', '33 Round'), ('34', '34 Round'), ('35', '35 Round'), ('36', '36 Round'), ('37', '37 Round'), ('38', '38 Round'), ('c_16', '챔스 16강')], default='1round', max_length=100)),
                ('league', models.CharField(choices=[('england', '프리미어리그'), ('spain', '라리가리그'), ('france', '리그앙'), ('german', '분데스리가')], default='england', max_length=100)),
                ('match_date', models.DateTimeField()),
                ('result', models.CharField(blank=True, choices=[('win', 'WIN'), ('draw', 'DRAW'), ('lose', 'LOSE')], max_length=10, null=True)),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
                ('strategy', models.CharField(choices=[('4-2-3-1', 'strategy_4-2-3-1'), ('3-5-2', 'strategy_3-5-2')], default='strategy_4-2-3-1', max_length=100, null=True)),
            ],
            options={
                'ordering': ('-match_date',),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='data/football/player')),
                ('review_photo', models.ImageField(null=True, upload_to='data/football/player/review_image')),
                ('birth', models.DateField()),
                ('nation', models.CharField(blank=True, choices=[('germany', 'German'), ('france', 'France'), ('spain', 'Spain'), ('england', 'England'), ('czech', 'Czech')], max_length=200, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PlayerSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('2017', '2017'), ('2018', '2018')], default='2017', max_length=100)),
                ('league', models.CharField(choices=[('england', '프리미어리그'), ('spain', '라리가리그'), ('france', '리그앙'), ('german', '분데스리가')], default='england', max_length=100)),
                ('back_number', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99)], default=1)),
                ('position_number', models.IntegerField(default=1)),
                ('position', models.CharField(choices=[('FW', 'FW'), ('MF', 'MF'), ('DF', 'DF'), ('GK', 'GK')], default='GK', max_length=10)),
                ('goal', models.PositiveIntegerField(default=0)),
                ('assist', models.PositiveIntegerField(default=0)),
                ('game', models.PositiveIntegerField(default=0)),
                ('point', models.PositiveIntegerField(default=0)),
                ('ratio', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_information', to='data.Player')),
            ],
            options={
                'ordering': ('position_number', 'position'),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='data/football/team')),
                ('stadium', models.CharField(max_length=200)),
                ('league', models.CharField(choices=[('england', '프리미어리그'), ('spain', '라리가리그'), ('france', '리그앙'), ('german', '분데스리가')], default='england', max_length=200)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='TeamSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('2017', '2017'), ('2018', '2018')], default='2017', max_length=100)),
                ('league', models.CharField(choices=[('england', '프리미어리그'), ('spain', '라리가리그'), ('france', '리그앙'), ('german', '분데스리가')], default='england', max_length=200)),
                ('ranking', models.IntegerField(default=1)),
                ('win', models.PositiveIntegerField(default=0)),
                ('draw', models.PositiveIntegerField(default=0)),
                ('lose', models.PositiveIntegerField(default=0)),
                ('benefit', models.IntegerField(default=0)),
                ('goal_benefit', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_season_information', to='data.Team')),
            ],
            options={
                'ordering': ('league', 'season', 'ranking'),
            },
        ),
        migrations.CreateModel(
            name='UserPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(choices=[('login', 'login'), ('review', 'review'), ('free', 'free'), ('comment', 'comment'), ('vote', 'vote'), ('correct_vote', 'correct_vote'), ('easy_point', 'easy_point'), ('spend', 'spend')], max_length=20, null=True)),
                ('point', models.PositiveIntegerField(blank=True, default=0)),
                ('total_experience', models.PositiveIntegerField(blank=True, default=0)),
                ('point_name', models.CharField(blank=True, max_length=20, null=True)),
                ('daily_check', models.IntegerField(blank=True, default=0, null=True)),
                ('daily_review', models.IntegerField(blank=True, default=0, null=True)),
                ('daily_free', models.IntegerField(blank=True, default=0, null=True)),
                ('daily_comment', models.IntegerField(blank=True, default=0, null=True)),
                ('level', models.PositiveIntegerField(blank=True, default=1)),
                ('value', models.IntegerField(default=0)),
                ('recent_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('max_experience', models.PositiveIntegerField(blank=True, default=100)),
                ('experience', models.IntegerField(blank=True, default=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-point', 'user'),
            },
        ),
        migrations.AddField(
            model_name='playerseason',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_season_information', to='data.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_away_team', to='data.TeamSeason'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_home_team', to='data.TeamSeason'),
        ),
        migrations.AddField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_player1', to='data.PlayerSeason'),
        ),
        migrations.AddField(
            model_name='match',
            name='player10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_player10', to='data.PlayerSeason'),
        ),
        migrations.AddField(
            model_name='match',
            name='player11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_player11', to='data.PlayerSeason'),
        ),
        migrations.AddField(
            model_name='match',
            name='player12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_subplayer1', to='data.PlayerSeason'),
        ),
        migrations.AddField(
            model_name='match',
            name='player13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_subplayer2', to='data.PlayerSeason'),
        ),
        migrations.AddField(
            model_name='match',
            name='player14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_subplayer3', to='data.PlayerSeason'),
        ),
        migrations.AddField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_player2', to='data.PlayerSeason'),
        ),
        migrations.AddField(
            model_name='match',
            name='player3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_player3', to='data.PlayerSeason'),
        ),
        migrations.AddField(
            model_name='match',
            name='player4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_player4', to='data.PlayerSeason'),
        ),
        migrations.AddField(
            model_name='match',
            name='player5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_player5', to='data.PlayerSeason'),
        ),
        migrations.AddField(
            model_name='match',
            name='player6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_player6', to='data.PlayerSeason'),
        ),
        migrations.AddField(
            model_name='match',
            name='player7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_player7', to='data.PlayerSeason'),
        ),
        migrations.AddField(
            model_name='match',
            name='player8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_player8', to='data.PlayerSeason'),
        ),
        migrations.AddField(
            model_name='match',
            name='player9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_player9', to='data.PlayerSeason'),
        ),
    ]
