# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 14:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('created', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('discount_point', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-created', '-id'),
            },
        ),
        migrations.CreateModel(
            name='FantasyLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('position', models.CharField(choices=[('player1', 'player1'), ('player2', 'player2'), ('player3', 'player3'), ('player4', 'player4'), ('player5', 'player5'), ('player6', 'player6'), ('player7', 'player7'), ('player8', 'player8'), ('player9', 'player9'), ('player10', 'player10'), ('player11', 'player11')], max_length=10)),
                ('strategy', models.CharField(choices=[('strategy_4-2-3-1', 'strategy_4-2-3-1'), ('strategy_3-5-2', 'strategy_3-5-2')], default='strategy_4-2-3-1', max_length=15)),
            ],
            options={
                'ordering': ('user', 'name', 'position'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True)),
                ('point', models.IntegerField(default=0)),
                ('width', models.CharField(max_length=100, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('information', models.TextField()),
                ('image', models.ImageField(upload_to='product_image/')),
                ('is_active', models.BooleanField(default=True)),
                ('buyer', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-category', 'width'),
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='pointshop.Category')),
            ],
            options={
                'ordering': ('created', '-id'),
            },
        ),
        migrations.CreateModel(
            name='UsePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=200, null=True)),
                ('buy_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('use_point', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pointshop.Category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pointshop.Product')),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pointshop.ProductCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('buy_date', 'id'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='pointshop.ProductCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pointshop.Category'),
        ),
        migrations.AddField(
            model_name='fantasyleague',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pointshop.Product'),
        ),
        migrations.AddField(
            model_name='fantasyleague',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set([('category', 'width')]),
        ),
        migrations.AlterIndexTogether(
            name='fantasyleague',
            index_together=set([('user', 'name', 'position')]),
        ),
    ]
