# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 14:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(choices=[('free', '게시글'), ('comment', '댓글'), ('message', '쪽지'), ('etc', '기타')], max_length=10)),
                ('is_charge', models.BooleanField(default=False)),
                ('charge_reason', models.CharField(choices=[('0', '욕설, 비방, 반말'), ('1', '지역 비하 발언'), ('2', '일베'), ('9', '기타')], max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('charge_date', models.DateTimeField(auto_now_add=True)),
                ('result_now', models.CharField(choices=[('yes', '완료'), ('no', '대기')], default='no', max_length=10)),
                ('result', models.CharField(blank=True, choices=[('yellow', '경고(삭제)'), ('delete', '삭제'), ('maintain', '유지')], max_length=10, null=True)),
                ('result_date', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charge_set', to='administrator.Charge')),
                ('charge_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_from_user', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_content_type', to='contenttypes.ContentType')),
                ('result_who', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_who_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
