# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 14:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sort', models.CharField(choices=[('0', 'team'), ('1', 'player1'), ('2', 'player2'), ('3', 'player3'), ('4', 'player4'), ('5', 'player5'), ('6', 'player6'), ('7', 'player7'), ('8', 'player8'), ('9', 'player9'), ('10', 'player10'), ('11', 'player11'), ('12', 'player12'), ('13', 'player13'), ('14', 'player14')], max_length=15)),
                ('point', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('is_simple', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-id', '-match', 'player'),
            },
        ),
        migrations.CreateModel(
            name='BeforeReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sort', models.CharField(choices=[('0', 'strategy'), ('1', 'player1'), ('2', 'player2'), ('3', 'player3'), ('4', 'player4'), ('5', 'player5'), ('6', 'player6'), ('7', 'player7'), ('8', 'player8'), ('9', 'player9'), ('10', 'player10'), ('11', 'player11')], max_length=15)),
                ('strategy', models.CharField(blank=True, choices=[('strategy_3-5-2', '3-5-2'), ('strategy_4-2-3-1', '4-2-3-1')], max_length=15, null=True)),
            ],
            options={
                'ordering': ('-match', 'player', '-id'),
            },
        ),
        migrations.CreateModel(
            name='FreeBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(choices=[('free', '자유'), ('before', '프리뷰'), ('after', '경기후'), ('player', '선수')], default='free', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('read', models.IntegerField(blank=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('after_game_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footballboard_after_game', to='data.Match')),
                ('before_game_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footballboard_before_game', to='data.Match')),
                ('player_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footballboard_player_review', to='data.PlayerSeason')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='beforereview',
            name='freeboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_free.FreeBoard'),
        ),
        migrations.AddField(
            model_name='beforereview',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beforereview_match', to='data.Match'),
        ),
        migrations.AddField(
            model_name='beforereview',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beforereview_player', to='data.PlayerSeason'),
        ),
        migrations.AddField(
            model_name='beforereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beforereview_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='afterreview',
            name='freeboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board_free.FreeBoard'),
        ),
        migrations.AddField(
            model_name='afterreview',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afterreview_match', to='data.Match'),
        ),
        migrations.AddField(
            model_name='afterreview',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='afterreview_player', to='data.PlayerSeason'),
        ),
        migrations.AddField(
            model_name='afterreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afterreview_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
