# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 14:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_round', models.IntegerField(default=1)),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
                ('vote_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_result', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpoint_match', to='data.Match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('match', 'vote_date'),
            },
        ),
        migrations.CreateModel(
            name='VoteAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=255, null=True)),
                ('pic_answer', models.ImageField(blank=True, null=True, upload_to='survey')),
                ('is_transform', models.CharField(choices=[('letter', 'letter'), ('picture', 'picture')], default='letter', max_length=10)),
                ('is_show', models.BooleanField(default=True)),
                ('vote', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VoteQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_vote', models.DateTimeField()),
                ('end_vote', models.DateTimeField()),
                ('choice_num', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_sort', models.CharField(choices=[('select', 'select'), ('write', 'write'), ('picture', 'picture')], default='select', max_length=50)),
            ],
            options={
                'ordering': ('-id', '-created'),
            },
        ),
        migrations.CreateModel(
            name='VoteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write_answer', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_sort', models.CharField(choices=[('select', 'select'), ('write', 'write'), ('picture', 'picture')], default='select', max_length=50)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_user_question', to='arsenal.VoteQuestion')),
                ('select_answer', models.ManyToManyField(blank=True, related_name='vote_user_answer', to='arsenal.VoteAnswer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_user_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='voteanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_answer_question', to='arsenal.VoteQuestion'),
        ),
    ]
